#!/bin/sh

echo -n "Waiting for health.jsp"
RESULT=""
while [ "x$RESULT" != "x1" ]; do 
	echo -n "."
	RESULT=`curl -s http://needlesscompass-nmalik.rhcloud.com/health.jsp`; 
	sleep 1
done;
echo "done"
